version: '3.1'

services:

  order-db:
    container_name: "eshop-order-db"
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: giancotsu
      POSTGRES_PASSWORD: root
      POSTGRES_DB: eshop-order