version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:management
    restart: unless-stopped
    container_name: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=giancotsu
      - RABBITMQ_DEFAULT_PASS=root
volumes:
  rabbitmq-volume:

