
# ==============================================================
# = Eureka Server
# = Dash: http://localhost:8761
# ==============================================================

server:
  port: 8761
  tomcat:
    threads:
      max: 5

spring:
  application:
    name: Eureka

# ==============================================================
# = Config Server
# ==============================================================

  config:
    import: configserver:http://localhost:8888?fail-fast=true&max-attempts=15&max-interval=1500&multiplier=1.2&initial-interval=1100
  cloud:
    config:
      name: EshopEureka
      profile: conf