
# ==============================================================
# = Eureka Server
# = Dash: http://localhost:8761
# ==============================================================

server:
  port: 8761
  tomcat:
    threads:
      max: 5

spring:
  application:
    name: Eureka

# ==============================================================
# = Eureka Parameters
# ==============================================================
eureka:
  instance:
    hostname: localhost

    preferIpAddress: false
  # ==============================================================
  # = Server settings
  # ==============================================================
  server:
    enableSelfPreservation: true
    responseCacheUpdateIntervalMs: 60000
    evictionIntervalTimerInMs: 30000
    waitTimeInMsWhenSyncEmpty: 5
  # ==============================================================
  # = Client settings
  # ==============================================================
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/