version: '3.1'

services:

  inventory-db:
    container_name: "eshop-inventory-db"
    image: postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: giancotsu
      POSTGRES_PASSWORD: root
      POSTGRES_DB: eshop-inventory