version: '3.1'

services:

  user-db:
    container_name: "eshop-user-db"
    image: postgres
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: giancotsu
      POSTGRES_PASSWORD: root
      POSTGRES_DB: eshop-user